### ISSUE TITLE
AttributeError: 'staticmethod' object has no attribute '__name__'

### ISSUE THREAD

**Issue by veehaitch** [scottcwang/openssh_key_parser#1]
Thanks for the project!

Using the latest version `0.0.2` from PyPI, I see the following error:

```ShellSession
# python -m openssh_key id_ed25519 --passphrase hunter12
Traceback (most recent call last):
  File "/nix/store/k5lw9imni647dl2n10xvq9w4yb840a8l-python3-3.9.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/k5lw9imni647dl2n10xvq9w4yb840a8l-python3-3.9.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nix/store/0zgs6a1i93f3y7bqalvw1l6n63r7g91y-python3-3.9.9-env/lib/python3.9/site-packages/openssh_key/__main__.py", line 23, in <module>
    if file_contents.startswith(PrivateKeyList.OPENSSH_PRIVATE_KEY_HEADER):
  File "/nix/store/0zgs6a1i93f3y7bqalvw1l6n63r7g91y-python3-3.9.9-env/lib/python3.9/site-packages/openssh_key/utils.py", line 51, in __get__
    getattr(cls, self._getter.__name__)()
AttributeError: 'staticmethod' object has no attribute '__name__'
```

Version `0.0.1` works and all tests pass.

I'm using [`Nix`](https://nixos.org) with the following derivation, if that's of any help: https://github.com/NixOS/nixpkgs/compare/master...veehaitch:py3-openssh_key_parser

**Comment by scottcwang** [comment]
Thank you for the bug report, and for using the package!

This issue is because I was working in python 3.10, which [adds the `__name__` attribute](https://github.com/python/cpython/pull/25268) to `@staticmethod` and `@classmethod`. I didn't realise this was new to python 3.10. Sorry about that.

I will fix the `readonly_static_property` so it takes a `str` name, not the `staticmethod` object itself. Would you need this fix soon?

**Comment by veehaitch** [comment]
Ah, okay, thanks for the quick response! 

I'm happy to use Python 3.10, that's not an issue. I'd just suggest to adapt `setup.py` if you don't plan to support prior versions in the near future:

https://github.com/scottcwang/openssh_key_parser/blob/c79b3643603211d930d9c7df57f0a945e0877ce3/setup.py#L21

Feel free to close this issue.

**Comment by scottcwang** [comment]
Good point! It is a little bit trickier than I thought to support the prior versions. In the future, I might overhaul this descriptor to be less clunky.
